# Generated by Django 4.0.2 on 2022-02-07 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statii', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='statie',
            name='lat',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statie',
            name='long',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
